<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="com.team3.gdx.tests.CustomerTests" tests="4" skipped="0" failures="1" errors="0" timestamp="2023-04-19T09:49:01" hostname="DESKTOP-7A0IUD0" time="0.36">
  <properties/>
  <testcase name="testCustomerAtPosition" classname="com.team3.gdx.tests.CustomerTests" time="0.144">
    <failure message="java.lang.AssertionError: expected:&lt;com.team3gdx.game.entity.Customer@122592e5&gt; but was:&lt;null&gt;" type="java.lang.AssertionError">java.lang.AssertionError: expected:&lt;com.team3gdx.game.entity.Customer@122592e5&gt; but was:&lt;null&gt;
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:120)
	at com.team3.gdx.tests.CustomerTests.testCustomerAtPosition(CustomerTests.java:107)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:258)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at com.team3.gdx.tests.GdxTestRunner.render(GdxTestRunner.java:59)
	at com.badlogic.gdx.backends.headless.HeadlessApplication.mainLoop(HeadlessApplication.java:128)
	at com.badlogic.gdx.backends.headless.HeadlessApplication$1.run(HeadlessApplication.java:93)
</failure>
  </testcase>
  <testcase name="testCustomerDeletion" classname="com.team3.gdx.tests.CustomerTests" time="0.078"/>
  <testcase name="testCustomerSpawn" classname="com.team3.gdx.tests.CustomerTests" time="0.07"/>
  <testcase name="testIncorrectCustomerZone" classname="com.team3.gdx.tests.CustomerTests" time="0.015"/>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
